# @package _global_
optimizer_type: "differentiable"

differentiable:
  learning_rate: 0.01
  max_iterations: 1000
  convergence_threshold: 0.000001

  # Soft selection parameters
  temperature: 0.1
  temperature_schedule: "constant" # constant, linear, exponential

  # Architecture
  hidden_dims: [64, 32]
  activation: "relu"

  # Regularization
  l2_reg: 0.0001
  dropout_rate: 0.1

  # Sampling parameters for differentiable functions
  vocab_angle_samples: 20 # Number of (α, β) angle combinations to sample for vocabulary
  vocab_hole_samples: 100 # Number of hole combinations per angle for vocabulary
  truss_angle_samples: 20 # Number of α angles to sample for truss complexity
  truss_hole_samples: 50 # Number of hole combinations per angle for truss complexity

  # Feasibility parameters
  truss_length_min: 3.0
  truss_length_max: 15.0
